### ISSUE TITLE
Suppress status update console.log calls

### ISSUE THREAD

**Issue by lachlansleight** [ibrod83/nodejs-web-scraper#11]
Firstly, thanks so much for making this, it's a fantastic package that I use all the time!

I have a small feature request:

It would be nice if it were possible to suppress the 'currentlyRunning' and 'overall requests' `console.log` calls. I'm scraping many, many pages and these logs fill up my console and make it harder for me to see what's actually going on in my program.

It's easy enough for me to comment them out, but it would be cool if there was something like a property on the Scraper object like `supressStatusUpdates` that defaults to false. Just an idea!

**Comment by ibrod83** [comment]
Lol, i was just thinking about this yesterday! Yes, i will do it :-)

**Comment by ibrod83** [comment]
Added a "showConsoleLogs"(default is true) property to the scraper config, in the version(3.3.0)

**Comment by lachlansleight** [comment]
Nice one! Thanks :D
