### ISSUE TITLE
Failed to open puppeteer on Heroku

### ISSUE THREAD

**Issue by MelodicCrypter** [ibrod83/nodejs-web-scraper#12]
I followed probable-solution here:

 https://stackoverflow.com/questions/63177218/puppeteer-on-heroku-failed-to-launch-the-browser-process

I already set up the buildpack, but now the issue is the --no-sandbox config. I checked your package and it seems you're using a customized version of puppeteer? I'm not sure. How to add the --no-sandbox config before you launch the puppeteer? 

Thanks!

@ibrod83

**Comment by ibrod83** [comment]
Unfortunately i didn't really think through the whole Puppeteer config thing. I will need to add this option, will do it in the upcoming days. sorry for the inconvenience

**Comment by MelodicCrypter** [comment]
@ibrod83  okay, thanks! While waiting for your version bump, is there a way I can patch your package temporarily?

**Comment by ibrod83** [comment]
I've updated the program to 4.2.0. Now you can pass your "args" array through scraper.config.puppeteerConfig.args. Refer to the docs. 
please inform me if something goes wrong.

**Comment by MelodicCrypter** [comment]
@ibrod83 thanks! I will try it this week and update you.

**Comment by MelodicCrypter** [comment]
@ibrod83 I'm still getting some error:

Error:
<img width="651" alt="Screen Shot 2020-12-17 at 1 10 24 AM" src="https://user-images.githubusercontent.com/18341500/102381898-c0957800-4004-11eb-9eab-f05c0d5488e8.png">

Screenshot from the GraphQL Playground

My config:

`{
     usePuppeteer: true,
     puppeteerConfig: {
          timeout: 40000,
          headless: true,
          args: ['--no-sandbox', '--disable-setuid-sandbox'],     
      },
...
}`

I also tried, commenting out headless, coz it was noted that it can cause some delays. But still no effect.

This was deployed to Heroku and I have already included these build packages:
- https://github.com/jontewks/puppeteer-heroku-buildpack
- https://github.com/heroku/heroku-buildpack-chromedriver
- heroku/nodejs

Still, the error is present.

**Comment by ibrod83** [comment]
Well, i never tried the program on an actual serve like Heroku- only local(both Windows and Linux). I guess this is some Puppeteer/Heroku issue. Eventually my program just launches a rather standard Puppeteer instance behind the scenes, passing your configuration. I think you need to try  running some basic Puppeteer setup from Heroku(separate app), to inquire how/if it works.

Does your code work locally?

**Comment by MelodicCrypter** [comment]
Hi @ibrod83 I see. Yes, the app works fine on local, either headless or not, it still works. Only when deployed to Heroku. Okay let me test again this week and I'll just update here. Thanks!

**Comment by ibrod83** [comment]
In case it's still relevant, there was some big bug in my program. The various arguments you passed to Puppeteer didnt really go through. You can try it now.
