### ISSUE TITLE
How to setViewport in this library?

### ISSUE THREAD

**Issue by epliego** [ibrod83/nodejs-web-scraper#13]
Hi!

I need the browser to be in full screen, for that puppeteer has the option setViewport and I pass width and height to it. But in Nodejs Web Scraper I can't.

Thanks!

**Comment by ibrod83** [comment]
I see puppeteer has an option of defaultViewport. Try passing it to the puppeteerConfig option of the scraper, like this:
`new Scraper({
    puppeteerConfig:{
      defaultViewport: someValue...
    }
  })`
This feature of passing various puppeteer config options wasn't tested much, tell me it works for you.

**Comment by epliego** [comment]
> I see puppeteer has an option of defaultViewport. Try passing it to the puppeteerConfig option of the Sscraper's main config object, like this:
> `new Scraper({ puppeteerConfig:{ defaultViewport: someValue... } })`
> This feature of passing various puppeteer config options wasn't tested much, tell me it works for you.

Thanks for the reply!

And yes, i tried that.

Here is a piece of my code:
`const config = {
        usePuppeteer: true,
        puppeteerConfig: {
          timeout: 90000,
          waitUntil: 'networkidle2',
          headless: false, // If false (default) open chromium
          defaultViewport: null,
        },
        baseSiteUrl: 'https://www.page.com/',
        startUrl: 'https://www.page.com/',
        logPath: './logs/',
        showConsoleLogs: false, // Show in console logs
      };

      const scraper = new Scraper(config);

      const root = new Root();`

In defaultViewport, also tried defaultViewport: {width: 1344, height: 768}. But it doesn't work either.

**Comment by ibrod83** [comment]
Ok, it seems i made some horrible mistake in my last deploy, and didn't update the underlying puppeteer-simple module, which is my wrapper over puppeteer...dont know how this happened :D
I will fix this tomorrow...Thanks for bringing this to my attention!

**Comment by ibrod83** [comment]
Done. I also made defaultViewport:null as default. Update to the latest version and tell me if it works for you.

**Comment by epliego** [comment]
> Done. I also made defaultViewport:null as default. Update to the latest version and tell me if it works for you.

Hi @ibrod83, i tried that and works perfect =D.

Many thanks for your help.
