### ISSUE TITLE
Question: Is it possible to get img -> src?

### ISSUE THREAD

**Issue by Zhavii** [ibrod83/nodejs-web-scraper#20]
Just grabbing the URL from the img src rather than downloading the whole image.

**Comment by Zhavii** [comment]
Right, but of course a little bit more reading would bring me the answer:

`const condition = (cheerioNode) => {
        console.log(cheerioNode.attr('src'))
}

const image= new CollectContent('image', {condition})
`

**Comment by ibrod83** [comment]
:D
