### ISSUE TITLE
Transform via getElementContent

### ISSUE THREAD

**Issue by LydiaF** [ibrod83/nodejs-web-scraper#29]
Hi @ibrod83,

Thank you so much for this package, it is extremely useful.

I have a feature suggestion: ability to return objects from getElementContent. This way we can keep the data together.

At the moment I'm doing this...

```
const x = new CollectContent('a[id="some_id"]', {
    name: 'x',
    getElementContent: (a, b, c) => {
      const href = c.attr('href').substr(7)
      const html = c.html()
      return `${html}___${href}` // would like to return { html, href }
    },
  })
 ``` 
Something unexpected happens when you try to return an object, you get what you would get if you didn't have the getElementContent option.

Thanks for considering!

Lydia

**Comment by ibrod83** [comment]
Hey,
I'm not really working on this package anymore. Do you maybe want to do it yourself and create a PR?

**Comment by jamin84** [comment]
hey @LydiaF! Check out the latest version; I had wanted the same thing and submitted a PR to return all data types for getElementContent

**Comment by LydiaF** [comment]
> Hey, I'm not really working on this package anymore. Do you maybe want to do it yourself and create a PR?

Hey, sorry I didn't reply to this, don't remember reading :)

**Comment by LydiaF** [comment]
@jamin84 Sorry for slow response, but it's perfect, thank you v v much!
