### ISSUE TITLE
Scraping a list of URLs

### ISSUE THREAD

**Issue by cormip** [ibrod83/nodejs-web-scraper#4]
I have a non-sequential list of URLs from the same site that I wish to scrape, but I don't see an obvious/optimal way to do it. For example:

http://www.example.com/page?id=73
http://www.example.com/page?id=129
http://www.example.com/page?id=247
http://www.example.com/page?id=341
etc...

How would you suggest the best way to accomplish this would be given that `Scraper can have only one instance`?

**Comment by ibrod83** [comment]
After you have finished awaiting scraper.scrape(), call scraper.destroy(), and create your new instance.

**Comment by cormip** [comment]
Great! That worked. Thanks

**Comment by ibrod83** [comment]
I've uploaded a new version(3.1.0). There's no need to call scraper.destroy() anymore.
