### ISSUE TITLE
Scrape and return an entire webpage

### ISSUE THREAD

**Issue by barryrlmurphy** [ibrod83/nodejs-web-scraper#7]
Can this package scrape and return a given webpage?
Similar to this : https://www.npmjs.com/package/website-scraper
The use case I have is to be able to scrape a given URL, save off all of its HTML and assets and then load it in an iframe from my local project

**Comment by ibrod83** [comment]
Maybe this will help : https://github.com/ibrod83/nodejs-web-scraper#get-an-entire-html-file
