### ISSUE TITLE
(node:22539) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'alternativeSrc' of undefined

### ISSUE THREAD

**Issue by rthangam** [ibrod83/nodejs-web-scraper#8]
const { Scraper, Root, DownloadContent } = require('nodejs-web-scraper');

(async () => {

   const config = {
        baseSiteUrl: `https://spectator.sme.sk`,//Important to provide the base url, which is the same as the starting url, in this example.
        startUrl: `https://spectator.sme.sk/`,
        filePath: './images/',
        cloneImages: true,//Will create a new image file with an appended name, if the name already exists. Default is false. 
       }

    const scraper = new Scraper(config);

    const root = new Root();//Root corresponds to the config.startUrl. This object starts the entire process

    const images = new DownloadContent('img')//Create an operation that downloads all image tags in a given page(any Cheerio selector can be passed).

    root.addOperation(images);//We want to download the images from the root page, we need to Pass the "images" operation to the root.

    await scraper.scrape(root);//Pass the Root to the Scraper.scrape() and you're done.

})();    

While running the above script facing the following issue.

node:22484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
offlineCharts % node scraper.js
(node:22539) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'alternativeSrc' of undefined

**Comment by ibrod83** [comment]
Hey, i see the problem. While i resolve the issue, please do the following:
const images = new DownloadContent('img',{name:"images"})//Adding this just to have a config object

My code in DownloadContent is currently probably assuming the existence of a config object. Until i fix it, this will work :-)

**Comment by ibrod83** [comment]
fixed

**Comment by rthangam** [comment]
Thanks a lot
